- name: Upload to ESOUI
  uses: m00nyONE/esoui-upload@v1
  with:
    api_key: ${{ secrets.ESOUI_API_KEY }}
    addon_id: '123456'
    version: ${{ env.ADDON_VERSION }}
    zip_file: ${{ env.ZIP_FULL_NAME }}
    changelog_file: 'CHANGELOG.md'
